export const CRUD_ROUTE_ARGS = 'RESERVED_CRUD_ROUTE_ARGS';
export const CUSTOM_REQUEST_OPTIONS = 'RESERVED_CRUD_CUSTOM_REQUEST_OPTIONS';
export const CRUD_OPTIONS_METADATA = 'RESERVED_CRUD_OPTIONS_METADATA';
